export const CREATE_CANDIDATE = "CREATE_CANDIDATE";

export const RETRIEVE_CANDIDATES = "RETRIEVE_CANDIDATES";

export const UPDATE_CANDIDATE = "UPDATE_CANDIDATE";

export const DELETE_CANDIDATE = "DELETE_CANDIDATE";
